### ISSUE TITLE
Tracking item for minor adjustments to design and errata during spec authoring

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#342]
Microsoft proposals the following incidental adjustments for clarity/consistency post TC33:

- [x] In #341, we made the following additional changes for consistency in the removal of "instance" (see [this comment](https://github.com/oasis-tcs/sarif-spec/issues/341#issuecomment-472600437) for the full set of changes):

    - [x] Rename `runAutomationDetails.instanceId` to `runAutomationDetails.id`,.
    - [x] Rename `run.id` (of type `runAutomationDetails`) to `run.automationDetails`. Otherwise we'd end up with `run.id.id`, where the first `id` is a `runAutomationDetails` object and the second is a GUID-valued string. With this change, we end up with `run.automationDetails.id`, which reads naturally.

- [x] Per @kupsch: Modify date-time format to allow a date without a time.

- [x]  In #309 we made several more property and object name changes for consistency with "artifact". See [this comment](https://github.com/oasis-tcs/sarif-spec/issues/309#issuecomment-472919370) for the full set of changes.

- [x] In #319, we created a `multiformatMessageString` object and converted some `reportingDescriptor` properties to this type (`fullDescription` and `shortDescription`). We neglected to convert `reportingDescriptor.help` to this type, however.

**Comment by lgolding** [comment]
The following errata were noted during the ballot period and will be corrected after the ballot closes:

- [ ] Per @kupsch: In #291, in the JSON example there are a couple of errors in the SARIF data:

    - `results/0/locations/0/fullQualifiedLogicalName` should be **"/orders/0/productIds/1"**
    - `results/0/locations/0/logicalLocationIndex` should be **3**
    - `results/1/locations/0/logicalLocationIndex` should be **4**

- [ ] Per @kupsch: In #291, in the examples, clarify that the line numbers are not part of the JSON.

    **Jim**: I will do that by mentioning the convention in §2.2, "Format examples", and by italicizing the line numbers (not by coloring them, for accessibility reasons, although of course I could _both_ italicize and color them).

**Comment by lgolding** [comment]
Updated #182, which was about registering the SARIF MIME type, to cover this issue as well. Closing this issue as duplicate of #182.

**Comment by lgolding** [comment]
Oops accidentally closed, meant to close #343.

**Comment by lgolding** [comment]
@kupsch I made the changes you suggested. See §2.2 (Format examples), §3.10.3 (URIs that use the SARIF scheme), and §3.31.8 (logicalLocation kind property).

@michaelcfanning All items are address so I'm resolving/closing this issue.
